spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crypto_db
    username: postgres
    password: mysecret
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

  jdbc:
    template:
      query-timeout: 5000

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG

