spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crypto_db
    username: postgres
    password: mysecret
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
